FROM golang:1.12-alpine as gobuilder

ENV GO111MODULE=on

RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories; \
    echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories

RUN apk add --no-cache linux-headers gcc musl-dev git zeromq zeromq-dev libsodium-dev pkgconfig build-base bash && \
    apk add --no-cache \
        --virtual=.build-dependencies &&\
    ln -s locale.h /usr/include/xlocale.h && \
    rm /usr/include/xlocale.h

# Authentication needed to pull git modules from github.impcloud.net
RUN git config --global credential.helper store
ARG GIT_TOKEN
RUN set +x && echo "https://$GIT_TOKEN:x-oauth-basic@github.impcloud.net" > ~/.git-credentials

WORKDIR $GOPATH/src/github.impcloud.net/RSP-Inventory-Suite/product-data-service

COPY . .

RUN ./build.sh

FROM alpine:3.7 as builder

RUN echo http://nl.alpinelinux.org/alpine/v3.7/main > /etc/apk/repositories; \
    echo http://nl.alpinelinux.org/alpine/v3.7/community >> /etc/apk/repositories
    
RUN apk --no-cache add zeromq curl

RUN mkdir -p /rootfs/curl

RUN for filename in $( \
        ldd /usr/bin/curl \
        # extract unqiue names
        | grep -oE "/[^:]*" | awk '{print $1}' | sort -u); \        
    do \
      cp -duv $filename `realpath $filename` --parents /rootfs/curl/; \
    done

FROM busybox:1.30.1

# ZeroMQ libraries and dependencies
COPY --from=builder /lib/libc.musl-x86_64.so.1 /lib/
COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/
COPY --from=builder /usr/lib/libzmq.so.5.1.5 /usr/lib/
COPY --from=builder /usr/lib/libzmq.so.5 /usr/lib/
COPY --from=builder /usr/lib/libsodium.so.23 /usr/lib/ 
COPY --from=builder /usr/lib/libstdc++.so.6 /usr/lib/
COPY --from=builder /usr/lib/libgcc_s.so.1 /usr/lib/
COPY --from=builder /usr/lib/libcrypto.so.42 /usr/lib/
COPY --from=builder /usr/lib/libcrypto.so.42.0.0 /usr/lib/

# CURL libraries
COPY --from=builder /usr/bin/curl /usr/bin/
COPY --from=builder /rootfs/curl /

COPY --from=gobuilder /go/src/github.impcloud.net/RSP-Inventory-Suite/product-data-service/product-data-service /
COPY --from=gobuilder /go/src/github.impcloud.net/RSP-Inventory-Suite/product-data-service/res/docker /res/docker

ARG GIT_COMMIT=unspecified
LABEL git_commit=$GIT_COMMIT

CMD ["/product-data-service","-r","--profile=docker","--confdir=/res"]